/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aisino_server_HalSocket */

#ifndef _Included_com_aisino_server_HalSocket
#define _Included_com_aisino_server_HalSocket
#ifdef __cplusplus
extern "C" {
#endif
#undef com_aisino_server_HalSocket_DATA_LEN
#define com_aisino_server_HalSocket_DATA_LEN 5L
/*
 * Class:     com_aisino_server_HalSocket
 * Method:    createUdpSocket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aisino_server_HalSocket_createUdpSocket
  (JNIEnv *, jobject);

/*
 * Class:     com_aisino_server_HalSocket
 * Method:    sendUdpPacket
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_aisino_server_HalSocket_sendUdpPacket
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
